# Generated by Django 3.1.5 on 2021-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(help_text='The username of that sent this message', max_length=200)),
                ('content', models.TextField(help_text='The contents of the message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time at which the message was sent at')),
            ],
        ),
    ]
