# Generated by Django 3.1.7 on 2021-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210403_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text='Interests associated with this channel', related_name='channels', to='chat.Interest'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(help_text='Short description of interest name', max_length=80),
        ),
    ]
