#!/usr/bin/env bash
# This script will be used to spin up the development servers for all the salve applications

# directory path of django development server
backend_folder="server"
# directory path of nuxt development server
frontend_folder="client"

# Start all the servers
{ cd "$backend_folder" && poetry run python3 manage.py runserver 0.0.0.0:8000 & \
  cd "$frontend_folder" && yarn dev; }
# { cd "$backend_folder" && poetry run python3 manage.py runserver 0.0.0.0:8000 & \
#   cd "$frontend_folder" && yarn dev & \
#   cd "$documentation_folder" && yarn start; }
