# Generated by Django 3.1.5 on 2021-04-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='contact',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(default='hello', help_text='The author of this message', max_length=200),
            preserve_default=False,
        ),
    ]
